### ISSUE TITLE
dúvida scripts

### ISSUE THREAD

**Issue by daniloagostinho** [willianjusten/script-dev#2]
Olá WIlian tudo bem?

Este script roda no Fedora também? Não estou seguindo configurar aqui. 

Abraço!

**Comment by daniloagostinho** [comment]
Já consegui rodar aqui Wilian, de qualquer forma obrigado! Parabéns pelo script muito bom! ;)

**Comment by willianjusten** [comment]
=)
Ele é um script debian based, mas com alguns ajustes, consegue funcionar no fedora de boa sim.
