### ISSUE TITLE
Criação de novos itens na lista

### ISSUE THREAD

**Issue by wmarquardt** [willianjusten/script-dev#7]
Para criar novos itens na lista, como posso dar continuidade ao ID?

**Comment by willianjusten** [comment]
Como o  número de itens vai ultrapassar o alfabeto, eu aconselho a fazer um refactor, modificando para números e então fazendo uma verificação melhor que `~=`. 

Eu infelizmente não tenho mais Linux para fazer os testes, mas quem quiser fazer e ajudar os outros, esteja super a vontade =D

**Comment by luizpicolo** [comment]
Corrigido #10
